# Generated by Django 5.0.3 on 2024-07-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_alter_curso_nivel_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='nivel',
        ),
        migrations.AddField(
            model_name='matricula',
            name='periodo',
            field=models.CharField(choices=[('N', 'Noturno'), ('V', 'Vespertino'), ('M', 'Matutino')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('A', 'Avançado'), ('I', 'Intermediário'), ('B', 'Básico')], default='B', max_length=1),
        ),
    ]
